# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@4.7

jobs:
  build_linux:
    docker:
      - image: cimg/node:14.17.6
    steps:
      - checkout
      - run: npm ci
      - run: bash sync-binaries.sh
      - run: bash build-linux.sh
      - run: sudo apt update
      - run: sudo apt install python3-pip
      - run: sudo pip3 install --upgrade b2
      - run: b2 authorize-account $B2_KEYID $B2_APPKEY
      - run: ls
      - run: b2 upload-file ./dist/*.tar.xz b2://geph-dl/STAGING/
  build_windows:
    docker:
      - image: cimg/node:14.17.6
    steps:
      - checkout
      - run: sudo apt update && sudo apt install wine && sudo dpkg --add-architecture i386 && sudo apt-get update && sudo apt-get install wine32
      - run: npm ci
      - run: bash sync-binaries.sh
      - run: bash build-windows.sh
      - run: sudo apt install python3-pip
      - run: sudo pip3 install --upgrade b2
      - run: b2 authorize-account $B2_KEYID $B2_APPKEY
      - run: b2 upload-file ./dist/*.exe b2://geph-dl/STAGING/

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  sample: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - build_linux:
          context:
            - master
      - build_windows:
          context:
            - master
